CREATE TABLE CUSTOMER(
CUST_ID INT  PRIMARY KEY,
NAME VARCHAR(20)
);
INSERT INTO CUSTOMER VALUES(101,'shalabh');
INSERT INTO CUSTOMER VALUES(102,'AJAY');


CREATE TABLE ORDERS(
ORDER_ID INT,
CUST_ID INT  ,
AMOUNT NUMERIC(10,2),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
ON UPDATE CASCADE
ON DELETE CASCADE
) 

INSERT INTO ORDERS VALUES(188,101,10000);
INSERT INTO ORDERS VALUES(188,102,20000)
INSERT INTO ORDERS VALUES(188,104,20000)

UPDATE CUSTOMER SET CUST_ID = 99
WHERE CUST_ID = 101

DELETE FROM CUSTOMER
WHERE CUST_ID = 99

DROP TABLE ORDERS
DROP TABLE CUSTOMER

SELECT * FROM ORDERS
SELECT * FROM CUSTOMER
